[project]
name = "jwegis-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "zensical>=0.0.2",
]

[dependency-groups]
dev = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "pre-commit>=4.5.1",
]
