[project]
site_name = "John Wegis"
site_description = "John Wegis personal site"


site_author = "John Wegis"
site_url = "https://jwegis.github.io/"
copyright = """
Copyright &copy; 2025 John Wegis
"""
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[project.theme]
favicon = "assets/images/favicon.svg"
logo = "assets/images/logo.svg"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.analytics]
provider = "google"
property = "UA-322470-35"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/jwegis"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/jwegis"

[[project.extra.social]]
icon = "fontawesome/brands/twitter"
link = "https://twitter.com/jwegis"

[project.extra]
"google-site-verification" = "_BIy8QpJJf8DLDTSrlUcxrirTyMfpNAVcjXreBb62Rw"
generator = false
